### ISSUE TITLE
Run only selective tests

### ISSUE THREAD

**Issue by GagandeepSharma060** [specmatic/specmatic#1343]
Hi team , the filters thing that is mentioned in the documentation. Is it also possible if I am not using junit/java for my tests and if i just have the yaml files -> mention it in the specmatic.json and then run it through command line. I tried multiple ways but was not able to do so

    "start": "cross-env-file -p ./token.json  specmatic test --testBaseURL=https://abc.com  --junitReportDir=./test-output && node cleanup"

This is the start command I am using, need urgent help

**Comment by GagandeepSharma060** [comment]
And when we write --filter-name "xyz" , where should this xyz be present for that endpoint (example) to be hit or not hit. Please provide example. It will be great as I am stuck for this implementation

@harikrishnan83 @nashjain @rakeshpai

**Comment by pranavgawri** [comment]
@GagandeepSharma060 thanks for sharing issue you are facing. We will update you shortly.

**Comment by GagandeepSharma060** [comment]
@pranavgawri found out that the filters are applied on the path name itself. It is great but can we have some tagging kind of mechanism like we have in Cypress. 

Because filtering on the path names does not seem to be a great idea when dealing with a lot of services. 

Just a thought.

**Comment by pranavgawri** [comment]
@GagandeepSharma060, Thank you for sharing your experience and suggestion. We're glad you found a workable solution with path name filtering.
Your idea about implementing a tagging system similar to Cypress is interesting and could indeed be beneficial for filtering tests across multiple services. We've noted this as a enhancement for future consideration.
We appreciate your feedback as it helps us improve Specmatic. Thanks.

**Comment by pranavgawri** [comment]
Hi @GagandeepSharma060 ,

We have enhanced our `--filter` option and I hope it should be able to help you better in your use case. Here is a quick overview:

The new filtering system provides powerful capabilities that align well with API contract testing:

1. Filter by HTTP Method and Path:
```bash
specmatic test --filter="METHOD=POST" --filter="PATH=/api/employees"
```
2. Filter by Status Codes (including pattern matching):
```shell
specmatic test --filter-not="STATUS=4xx"  # Excludes all client errors
```
3. Advanced Combinations:
```shell
specmatic test --filter="PATH=/api/employees" --filter="METHOD=POST" --filter-not="STATUS=400,401,403"
```

These filters work directly with your API contract structure, making it natural to organize and run your tests based on your API's design.

Please find the full details in our documentation here: https://specmatic.io/documentation/contract_tests.html#selectively-running-tests-in-ci

Let us know how this works for you!

Thanks,
Pranav

**Comment by GagandeepSharma060** [comment]
Thanks for the quick response and change @pranavgawri , will try it out and get back to you for feedback or any issues .

I believe this feature would help others too

Just a question, can we filter through description of the test .... as in that way it will give a huge flexibility 


By description I mean we can have a dedicated field or use the fields like description or summary for a path
<img width="787" alt="image" src="https://github.com/user-attachments/assets/607be1c6-00e3-4a10-afd4-13dabf662ecc">

**Comment by pranavgawri** [comment]
Hi @GagandeepSharma060,

Thanks for the feedback about filtering by description/summary fields. I've opened a discussion thread to explore this further: [Filtering Tests by Description/Summary Fields](https://github.com/znsio/specmatic/discussions/1398#discussion-7390937)

Please take a look and share your thoughts there. Once you've reviewed the discussion, please feel free to go ahead and close this original issue.
Appreciate you helping us improve Specmatic!

Thanks,
Pranav

**Comment by GagandeepSharma060** [comment]
Hi @pranavgawri ...Thanks for the response. Justwanted to let you know that filtering by the Example name is not working for me..

Let me explain

--filter="EXAMLPE_NAME=ABC" is not working however. --filter-not="EXAMLPE_NAME=ABC" is working fine.

Can u please look into it

**Comment by pranavgawri** [comment]
Hi @GagandeepSharma060 ,

Thanks for sharing the issue you are facing. We are able to replicate it at our end, and will push the fix soon. 

I will update you on the same.

Thanks,
Pranav

**Comment by GagandeepSharma060** [comment]
Hi @pranavgawri , is this fixed?

**Comment by GagandeepSharma060** [comment]
Hi @pranavgawri  Can you please share an update on this

**Comment by harikrishnan83** [comment]
hello @GagandeepSharma060 , thanks for reviving this thread. Apologies for the slow response on this. The fix for this is not yet in. I will get back to you on this within the next week. Thanks.

**Comment by back2debug** [comment]
Hi Do you have an update on this? I would like to filter out monitoring endpoints from my tests. 
Following the syntax on the docs `--filter="PATH='/users,/products' || STATUS='200'"` gives 
`Reason: Error in filter expression: Unexpected token after infix operator`

**Comment by joelrosario** [comment]
Hi @tmart134, this has been resolved in a recent update. Please try with the latest version and let us know if it works for you. Thanks.

**Comment by GagandeepSharma060** [comment]
Hi @joelrosario , do we have the ability to run few tests out of the total based on some description/summary and not path/status/example name. some tagging mechanism?

**Comment by back2debug** [comment]
> Hi [@tmart134](https://github.com/tmart134), this has been resolved in a recent update. Please try with the latest version and let us know if it works for you. Thanks.

Hi! Do you when the version with the fix will be available in npm to install/update? I am running 2.7.5 and it looks like that is latest in npm 
@joelrosario

**Comment by back2debug** [comment]
Hi I updated to 2.7.8 via npm and the new filter feature still doesn't work.

I tried some directly from the [documentation](https://specmatic.io/documentation/contract_tests.html#selectively-running-tests-in-ci).

Running this `specmatic test --filter="PATH='/admin/*'"` results in `Unsuccessful Scenarios: "Load Error FAILED: Reason: Error in filter expression: Unexpected token after infix operator`

Running this `specmatic test --filter="METHOD='GET'"` results in `Unsuccessful Scenarios: "Load Error FAILED" Reason: Error in filter expression: Variable or constant value for 'GET' not found`

@joelrosario

**Comment by kaushall** [comment]
Hi @tmart134 This issue is specific to Specmatic npm package. We have identified and fixed this issue, it will be available in the next release of Specmatic npm package (>2.7.8).

**Comment by kaushall** [comment]
> Hi [@joelrosario](https://github.com/joelrosario) , do we have the ability to run few tests out of the total based on some description/summary and not path/status/example name. some tagging mechanism?

Currently it's not there, but we do have this feature in our roadmap.

**Comment by GagandeepSharma060** [comment]
Hi @kaushall IS the initial issue still open, I am still not able to filter tests based on examples names...... also My use case is to filter them by a substring of an example name...for example I should be able to run all the tests having examples containeing "abc"

Getting this error while using filter command with EXAMPLE-NAME=...
        Reason: Error in filter expression: Variable or constant value for 'EXAMPLE' not found

Please help

**Comment by kaushall** [comment]
Hi @GagandeepSharma060 Yes, it is an open item. I have seen the same issue while testing `EXAMPLE-NAME` filter where `-` is not interpreted correctly. But be assured the team is working on it, and soon it will be fixed and released.

**Comment by back2debug** [comment]
@kaushall hi i updated to the 2.9.0 via npm and still get the same error 

this is my command `specmatic test --filter="PATH!='/admin/*'" bundle.yml --testBaseURL=http://localhost`
error: `Unsuccessful Scenarios:  "Load Error FAILED"  Reason: Error in filter expression: Unexpected token after infix operator`
I tried a couple of different variations but had no success

**Comment by kaushall** [comment]
> [@kaushall](https://github.com/kaushall) hi i updated to the 2.9.0 via npm and still get the same error
> 
> this is my command `specmatic test --filter="PATH!='/admin/*'" bundle.yml --testBaseURL=http://localhost` error: `Unsuccessful Scenarios: "Load Error FAILED" Reason: Error in filter expression: Unexpected token after infix operator` I tried a couple of different variations but had no success

Please update to specmatic npm package version `2.9.1` and let us know if you're still facing the same issue or not.

**Comment by mik047** [comment]
Hello @tmart134, @GagandeepSharma060, hope the [fix provided](https://github.com/znsio/specmatic/issues/1343#issuecomment-2818912900) by @kaushall resolved the issue. Closing this issue now because of lack of activity. Please feel free to reopen if you have any questions on this. Thanks.
