### ISSUE TITLE
Duplicate URL in API coverage when using with FastAPI

### ISSUE THREAD

**Issue by barath121** [specmatic/specmatic#836]
**Description**
- Duplicate URLs in API coverage when using with FastAPI. 
- FastAPI usually mounts two url for an single route 
    - With / at the end 
    - Without / at the end
```
Started adapting route: /administrator/v1.0/bulk/{job_type}/import/ with methods: {'GET'}
Adapter result: url: /administrator/v1.0/bulk/{job_type}/import, methods: [GET]

Started adapting route: /administrator/v1.0/bulk/{job_type}/import with methods: {'GET'}
Adapter result: url: /administrator/v1.0/bulk/{job_type}/import, methods: [GET]
```
- These routes are treated as separate routes in api coverage table but these shoule be treated as one route
```
|       0% | /administrator/v1.0/bulk/{job_type}/import                                                                               | GET    |          |           0 | missing in spec |
|          |                                                                                                                          | POST   |          |           0 | missing in spec |
|     100% | /administrator/v1.0/bulk/{job_type}/import/                                                                              | GET    |      200 |           1 | covered         |
|          |                                                                                                                          |        |      400 |           1 | covered         |
|          |                                                                                                                          | POST   |      200 |           1 | covered         |
|          |                                                                                                                          |        |      400 |           1 | covered         |                                                                                                                       | POST   |      200 |           1 | covered         |
``` 
**Steps to reproduce**
1. Create an flask server with some routes.
2. Create an API specification for the same.
3. Run specmatic contract test and check the coverage table.

**Expected behaviour**
Same routes ending with and without / should be treated as an single route.

**System Information:**
 - OS & version: MacOS 12.4
 - Specmatic version: 0.81.0(Node Wrapper)
 - JDK version: 11.0.16

**Comment by harikrishnan83** [comment]
@barath121 Thanks for reaching out. Need a few clarifications.

You are referring to a Flask app, however in the "System Information" section you have mentioned Specmatic "node wrapper". Did you mean to say "Python wrapper". This was fixed quite some time ago (0.15.1).

Can you please check on the latest Python wrapper [release 0.22.0](https://github.com/znsio/specmatic-python-extensions/releases/tag/0.22.0)?

**Comment by barath121** [comment]
@harikrishnan83 Sorry we were running specmatic python wrapper 0.15.1 but still are facing this issue. I will try updating to the latest version and check if this issue still exists and update here.

**Comment by jaydeepk** [comment]
Thanks for the update @barath121 
From the snapshot that you have posted, it seems that the trailing slash does get stripped out from the route ( see the Adapter result below)

```
Started adapting route: /administrator/v1.0/bulk/{job_type}/import/ with methods: {'GET'}
Adapter result: url: /administrator/v1.0/bulk/{job_type}/import, methods: [GET] 
```

So the routes inferred from the FastApi app will not have the trailing slashes.  
However, inspite of this we still see duplicate routes in the coverage report.  
One possible reason could be that the route is defined with a trailing slash in the spec.   
Since the coverage report indicates 100% coverage for the route with the trailing slash, it means that this is the route that got tested.
Could you please check an confirm if the spec has the route defined with the trailing slash?
If yes, then could you please try removing the trailing slash from the spec and re-run the tests.

**Comment by barath121** [comment]
Thanks for the help @jaydeepk , Spec had the / in it.
